<a href="https://colab.research.google.com/github/OmarMuhammed77/Diabetes_Risk_Prediction/blob/main/Diabetes_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loading and understanding the data**

In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer


from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

import warnings
warnings.filterwarnings('ignore')

In [186]:
df=pd.read_csv("diabetes_risk.csv")
df.head()

,patient_id,age,gender,city,bmi,family_history_diabetes,physical_activity_level,diet_type,smoking_status,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm,income_bracket,diabetes_risk
0,1,47,Female,Mumbai,26.5,Yes,Sedentary,Vegetarian,Never,Never,9.0,8,178,7.3,146,90,107.1,High,Low
1,2,53,Female,Mumbai,20.5,Yes,Moderate,Vegetarian,Never,Never,7.0,6,152,6.9,156,100,93.8,Low,Low
2,3,47,Male,Thane,31.3,No,Moderate,Non-Vegetarian,Current,Regular,7.0,7,168,6.6,150,102,113.5,Low,High
3,4,41,Male,Bengaluru,22.8,No,Sedentary,Non-Vegetarian,Never,Never,9.0,5,155,6.7,126,92,109.6,Middle,Low
4,5,57,Female,Bengaluru,16.7,No,Sedentary,Non-Vegetarian,Current,Occasional,6.5,10,188,6.7,130,90,80.8,High,Low

In [187]:
df.shape

(15000, 19)

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                15000 non-null  int64
 1   age                       15000 non-null  int64
 2   gender                    15000 non-null  object
 3   city                      15000 non-null  object
 4   bmi                       15000 non-null  float64
 5   family_history_diabetes   15000 non-null  object
 6   physical_activity_level   15000 non-null  object
 7   diet_type                 15000 non-null  object
 8   smoking_status            14528 non-null  object
 9   alcohol_consumption       11212 non-null  object
 10  hours_sleep_per_night     15000 non-null  float64
 11  stress_level              15000 non-null  int64
 12  fasting_blood_sugar       15000 non-null  int64
 13  hba1c_level               15000 non-null  float64
 14  blood_pressure_systolic   15000 non-null  int64
 15  blood_pressure_diastolic  15000 non-null  int64
 16  waist_circumference_cm    15000 non-null  float64
 17  income_bracket            14537 non-null  object
 18  diabetes_risk             15000 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 2.2+ MB

In [189]:
df.describe()

,patient_id,age,bmi,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,blood_pressure_diastolic,waist_circumference_cm
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,44.333667,23.062260,7.309860,5.941200,168.789933,6.878387,139.496200,86.256933,100.207933
std,4330.271354,10.383753,4.046391,1.109372,2.148406,38.365822,0.843276,12.660785,8.386529,10.760331
min,1.000000,18.000000,15.000000,3.000000,1.000000,72.000000,4.800000,80.000000,50.000000,73.200000
25%,3750.750000,38.000000,20.100000,6.700000,4.000000,145.000000,6.300000,130.000000,80.000000,92.500000
50%,7500.500000,45.000000,22.700000,7.000000,6.000000,165.000000,6.800000,140.000000,88.000000,99.300000
75%,11250.250000,52.000000,25.600000,8.000000,7.000000,189.000000,7.300000,150.000000,90.000000,106.900000
max,15000.000000,80.000000,40.800000,12.000000,10.000000,400.000000,13.400000,200.000000,120.000000,148.200000

# **Checking Outliers**

In [190]:
# checkOutliers=list(df.select_dtypes(include='number'))
# checkOutliers.pop(0)
# print(checkOutliers)

In [191]:
# n_cols = 2
# n_rows = int(np.ceil(len(checkOutliers) / n_cols))

# fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 5 * n_rows))

# axes = axes.flatten()

# for i, col in enumerate(checkOutliers):
#     sns.boxplot(data=df, y=col, ax=axes[i], palette='magma',whis=1.5)
#     axes[i].set_title(f'Boxplot of {col}', fontsize=12)
#     axes[i].set_xlabel('')
#     axes[i].set_ylabel(col)

# for j in range(i + 1, len(axes)):
#     fig.delaxes(axes[j])

# plt.tight_layout()
# plt.show()

# **Spliting train/test**

In [192]:
df.drop(columns='patient_id', inplace=True)

In [193]:
x = df.drop(columns=['diabetes_risk'])
y = df['diabetes_risk']

In [194]:
x_train, x_test, y_train, y_test = train_test_split(x , y, test_size=0.2, random_state=42, stratify=y)

In [195]:
display(f"x_train shape -> {x_train.shape}")
display(f"x_test shape -> {x_test.shape}")
display(f"y_train shape -> {y_train.shape}")
display(f"y_test shape -> {y_test.shape}")

'x_train shape -> (12000, 17)'

'x_test shape -> (3000, 17)'

'y_train shape -> (12000,)'

'y_test shape -> (3000,)'

# **Handling Nulls**

In [196]:
df.isnull().sum()

age                            0
gender                         0
city                           0
bmi                            0
family_history_diabetes        0
physical_activity_level        0
diet_type                      0
smoking_status               472
alcohol_consumption         3788
hours_sleep_per_night          0
stress_level                   0
fasting_blood_sugar            0
hba1c_level                    0
blood_pressure_systolic        0
blood_pressure_diastolic       0
waist_circumference_cm         0
income_bracket               463
diabetes_risk                  0
dtype: int64

In [197]:
numeric_features = x_train.select_dtypes(include=np.number).columns
categorical_features = x_train.select_dtypes(include='object').columns

print("Numerical:", list(numeric_features))
print("Categorical:", list(categorical_features))

Numerical: ['age', 'bmi', 'hours_sleep_per_night', 'stress_level', 'fasting_blood_sugar', 'hba1c_level', 'blood_pressure_systolic', 'blood_pressure_diastolic', 'waist_circumference_cm']
Categorical: ['gender', 'city', 'family_history_diabetes', 'physical_activity_level', 'diet_type', 'smoking_status', 'alcohol_consumption', 'income_bracket']

In [198]:
#Handling NULLS on numeric columns

num_imputer = SimpleImputer(strategy='median')

x_train[numeric_features] = num_imputer.fit_transform(x_train[numeric_features])
x_test[numeric_features] = num_imputer.transform(x_test[numeric_features])

In [199]:
#Handling NULLS categorical columns
cat_imputer = SimpleImputer(strategy='most_frequent')

x_train[categorical_features] = cat_imputer.fit_transform(x_train[categorical_features])
x_test[categorical_features] = cat_imputer.transform(x_test[categorical_features])

# **Encoding**

In [200]:
(x_train.select_dtypes(include='object')).info()

<class 'pandas.core.frame.DataFrame'>
Index: 12000 entries, 7666 to 1046
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   12000 non-null  object
 1   city                     12000 non-null  object
 2   family_history_diabetes  12000 non-null  object
 3   physical_activity_level  12000 non-null  object
 4   diet_type                12000 non-null  object
 5   smoking_status           12000 non-null  object
 6   alcohol_consumption      12000 non-null  object
 7   income_bracket           12000 non-null  object
dtypes: object(8)
memory usage: 843.8+ KB

In [201]:
# converting ordinal categories into numerical
# [alcohol_consumption, income_bracket ,physical_activity_level]

activity_mapping = {
    'Sedentary': 0,
    'Moderate': 1,
    'Active': 2
}

alcohol_mapping = {
    'Never': 0,
    'Occasional': 1,
    'Regular': 2
}

income_mapping = {
    'Low': 0,
    'Middle': 1,
    'High': 2
}

x_train['physical_activity_level'] = x_train['physical_activity_level'].map(activity_mapping)
x_test['physical_activity_level'] = x_test['physical_activity_level'].map(activity_mapping)

x_train['alcohol_consumption'] = x_train['alcohol_consumption'].map(alcohol_mapping)
x_test['alcohol_consumption'] = x_test['alcohol_consumption'].map(alcohol_mapping)

x_train['income_bracket'] = x_train['income_bracket'].map(income_mapping)
x_test['income_bracket'] = x_test['income_bracket'].map(income_mapping)

In [202]:
#binary maping for [family_history_diabetes]

binary_mapping = {
    'No': 0,
    'Yes': 1
}

x_train['family_history_diabetes'] = x_train['family_history_diabetes'].map(binary_mapping)
x_test['family_history_diabetes'] = x_test['family_history_diabetes'].map(binary_mapping)

In [203]:
#one hot encoder for nominal features
# ['gender', 'city', 'diet_type', 'smoking_status']

nominal_cols= list(x_train.select_dtypes(include='object'))

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

x_train_encoded = encoder.fit_transform(x_train[nominal_cols])
x_test_encoded = encoder.transform(x_test[nominal_cols])

In [204]:
x_train_encoded = pd.DataFrame(
    x_train_encoded,
    columns=encoder.get_feature_names_out(nominal_cols),
    index=x_train.index
)

x_test_encoded = pd.DataFrame(
    x_test_encoded,
    columns=encoder.get_feature_names_out(nominal_cols),
    index=x_test.index
)

In [205]:
# data_info(x_train_encoded)

In [206]:
x_train = x_train.drop(columns=nominal_cols,axis=1)
x_test = x_test.drop(columns=nominal_cols,axis=1)

x_train = pd.concat([x_train, x_train_encoded], axis=1)
x_test = pd.concat([x_test, x_test_encoded], axis=1)

# **Scaling**

In [207]:
X_train_scaled = x_train.copy()
X_test_scaled = x_test.copy()

In [208]:
numeric_features

Index(['age', 'bmi', 'hours_sleep_per_night', 'stress_level',
       'fasting_blood_sugar', 'hba1c_level', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'waist_circumference_cm'],
      dtype='object')

In [209]:
#scaling

scaler = StandardScaler()

X_train_scaled[numeric_features]=scaler.fit_transform(X_train_scaled[numeric_features])
X_test_scaled[numeric_features]=scaler.transform(X_test_scaled[numeric_features])

In [210]:
X_train_scaled

,age,bmi,family_history_diabetes,physical_activity_level,alcohol_consumption,hours_sleep_per_night,stress_level,fasting_blood_sugar,hba1c_level,blood_pressure_systolic,...,city_Surat,city_Thane,city_Visakhapatnam,diet_type_Non-Vegetarian,diet_type_Pescatarian,diet_type_Vegan,diet_type_Vegetarian,smoking_status_Current,smoking_status_Former,smoking_status_Never
7666,0.840720,0.058816,0,1,0,-1.550901,0.032358,-0.514431,-1.040454,1.377183,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
136,0.358651,-0.089876,0,0,0,1.524265,-0.433220,-0.566589,-0.210328,0.432658,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
5808,-2.051693,-0.858113,0,2,0,-0.284656,-0.898798,-1.453273,-1.514812,-0.984129,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
9042,0.358651,1.595290,0,0,0,-0.284656,1.429092,0.007148,-0.091739,0.983631,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
13895,-0.027004,-0.535949,0,1,1,-0.284656,-2.295532,0.841674,0.738387,-0.590577,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7779,-1.183969,-0.858113,1,2,1,-1.189117,1.894670,-0.227563,0.026851,-1.535102,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3404,0.937134,-1.328968,1,2,0,-0.284656,-0.898798,-1.088168,-0.803275,0.039106,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
6107,0.744306,-0.783767,0,0,0,1.433819,-0.433220,-0.436194,-0.684686,0.826210,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
12524,0.551479,-0.882895,0,2,0,-1.189117,-0.898798,-0.253642,0.501208,-1.535102,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1046,-0.412659,-0.833331,0,0,1,-0.284656,-0.433220,-1.401115,-0.921865,0.039106,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

# **Logistic Regression**

In [211]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [212]:
# Training
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [213]:
# Prediction
y_pred = model.predict(X_test_scaled)

In [214]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("---"*20)
print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.7966666666666666
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

        High       0.81      0.73      0.77       450
         Low       0.86      0.91      0.89      1800
    Moderate       0.61      0.56      0.58       750

    accuracy                           0.80      3000
   macro avg       0.76      0.73      0.75      3000
weighted avg       0.79      0.80      0.79      3000

# **Logistic Regression** -> (lasso)

In [215]:
model_lasso = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    max_iter=1000,
    C= 0.1,
    random_state=42
)

In [216]:
model_lasso.fit(X_train_scaled, y_train)

LogisticRegression(C=0.1, max_iter=1000, penalty='l1', random_state=42,
                   solver='liblinear')

In [217]:
y_pred_lasso = model_lasso.predict(X_test_scaled)

In [218]:
accuracy_lasso = accuracy_score(y_test, y_pred_lasso)

print("Accuracy:", accuracy_lasso)

print("---"*20)
print("Classification Report:")
print(classification_report(y_test, y_pred_lasso))

Accuracy: 0.7723333333333333
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

        High       0.75      0.78      0.77       450
         Low       0.80      0.95      0.87      1800
    Moderate       0.63      0.34      0.44       750

    accuracy                           0.77      3000
   macro avg       0.73      0.69      0.69      3000
weighted avg       0.75      0.77      0.75      3000

# **Logistic Regression** -> (ridge)

In [219]:
model_ridge = LogisticRegression(
    penalty='l2',
    solver='lbfgs',
    max_iter=1000,
    C= 0.1,
    random_state=42
)

In [220]:
model_ridge.fit(X_train_scaled, y_train)

LogisticRegression(C=0.1, max_iter=1000, random_state=42)

In [221]:
y_pred_ridge = model_ridge.predict(X_test_scaled)

In [222]:
accuracy_ridge = accuracy_score(y_test, y_pred_ridge)

print("Accuracy:", accuracy_ridge)

print("---"*20)
print("Classification Report:")
print(classification_report(y_test, y_pred_ridge))

Accuracy: 0.7953333333333333
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

        High       0.82      0.72      0.77       450
         Low       0.86      0.91      0.89      1800
    Moderate       0.60      0.56      0.58       750

    accuracy                           0.80      3000
   macro avg       0.76      0.73      0.74      3000
weighted avg       0.79      0.80      0.79      3000

# **DecisionTreeClassifier**

In [223]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
dt_model = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

In [224]:
# Training
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [225]:
# Prediction
y_pred_dt = dt_model.predict(x_test)

In [226]:
# Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", accuracy_dt)

print("---"*20)

print("Classification Report:")
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.765
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

        High       0.80      0.62      0.70       450
         Low       0.85      0.89      0.87      1800
    Moderate       0.54      0.55      0.55       750

    accuracy                           0.77      3000
   macro avg       0.73      0.69      0.71      3000
weighted avg       0.76      0.77      0.76      3000

# **RandomForestClassifier**

In [227]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [228]:
# Training
rf_model.fit(x_train, y_train)

# Prediction
y_pred_rf = rf_model.predict(x_test)

In [229]:
# Accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", accuracy_rf)

print("---"*20)

print("Classification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.7786666666666666
------------------------------------------------------------
Classification Report:
              precision    recall  f1-score   support

        High       0.80      0.69      0.74       450
         Low       0.85      0.90      0.88      1800
    Moderate       0.57      0.53      0.55       750

    accuracy                           0.78      3000
   macro avg       0.74      0.71      0.72      3000
weighted avg       0.77      0.78      0.77      3000

# **Comparison of accuracy**

In [230]:
print("Logistic RegressionAccuracy:", accuracy)
print("--"*30)
print("Logistic Regression(lasso) Accuracy::", accuracy_lasso)
print("--"*30)
print("Logistic Regression(ridge) Accuracy:", accuracy_ridge)
print("--"*30)
print("Decision Tree Accuracy:", accuracy_dt)
print("--"*30)
print("Random Forest Accuracy:", accuracy_rf)

Logistic RegressionAccuracy: 0.7966666666666666
------------------------------------------------------------
Logistic Regression(lasso) Accuracy:: 0.7723333333333333
------------------------------------------------------------
Logistic Regression(ridge) Accuracy: 0.7953333333333333
------------------------------------------------------------
Decision Tree Accuracy: 0.765
------------------------------------------------------------
Random Forest Accuracy: 0.7786666666666666

# **Feature Selection**